# Generated by Django 5.0.2 on 2024-03-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gangaGen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_code',
            field=models.CharField(blank=True, default='12345', max_length=50, null=True, unique=True),
        ),
    ]
