# Generated by Django 5.0.2 on 2024-03-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gangaGen', '0002_alter_customuser_access_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='access_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
