# Generated by Django 5.0.2 on 2024-03-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gangaGen', '0003_alter_customuser_access_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('organism', models.CharField(max_length=100)),
                ('domains', models.CharField(max_length=255)),
            ],
        ),
    ]
